### ISSUE TITLE
vip_network_id non-existing parameter for elbv2

### ISSUE THREAD

**Issue by kucerakk** [opentelekomcloud/python-otcextensions#227] opened 2021-09-09 14:23 UTC
The following mapping seems to be wrong in https://github.com/opentelekomcloud/python-otcextensions/blob/master/otcextensions/sdk/elb/v2/load_balancer.py

```
 #: VIP netowrk ID
 vip_network_id = resource.Body('vip_network_id')
```

According the documentation https://docs.otc.t-systems.com/elb/doc/download/pdf/elb-api.pdf this parameter does not exist in ELBv2

Due to this update the functional tests are also failing for octavia-proxy on Zuul

**Comment by gtema** [comment] 2021-09-09 14:41
I doubt. This class is actually not used at all. We should clearly drop it (and maybe it causes some conflict), but the error (would be nice to see the error also) is most likely caused by trying to set this parameter while invoking the SDK/OTCE

**Comment by kucerakk** [comment] 2021-09-10 09:01
the functional tests of octavia-proxy clearly fails with error when using the latest version of otcextensions: 
```
b'{"faultcode": "Client", "faultstring": "Validation failure: Unrecognized attribute(s) \'vip_network_id\'", "debuginfo": null}'
```

using older version 0.20.0 the tests passes

This parameter vip_network_id mapping was introduced in version 0.21.0

**Comment by gtema** [comment] 2021-09-10 09:02
you can try locally dropping this file. I assume nothing will change

**Comment by kucerakk** [comment] 2021-09-10 12:34
you are right, the error in octavia tests has nothing to do with the parameter in otcextensions, but with the latest updates in the octavia_proxy code...going to make an issue there...

regardless of the error in octavia, I believe this parameter ```vip_network_id``` should not be in elbv2

and btw the error in octavia comes directly from neutron:

```
RESP BODY: {"NeutronError": {"detail": "", "type": "HTTPBadRequest", "message": "Unrecognized attribute(s) 'vip_network_id'"}}
```

**Comment by gtema** [comment] 2021-09-10 13:27
we are not really overriding octavia resources that we use for v2. Generally octavia-proxy should not even try passing vip_network_id. You get the error cause something tries to initialize it.
If this does not work perhaps we need to do same as with v3 and reimplement it on our side

**Comment by anton-sidelnikov** [comment] 2022-01-12 08:39
fixed in octavia-proxy

**Closed as completed by anton-sidelnikov** 2022-01-12 08:39 UTC
